# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :'prod-nginx-01' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.150',
  },
  :'prod-nginx-02' => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.151',
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
          vb.name = boxname.to_s
          end
          box.vm.provision "ansible" do |ansible|
          ansible.playbook = "nginx.yml"
          end
      end
   end
end
