# -*- mode: ruby -*-
# vi: set ft=ruby :
# Проект

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
  
    config.vm.define "node1" do |node1|
      node1.vm.network :private_network, ip: "192.168.56.150"
      node1.vm.hostname = "node1.otus.local"
      node1.vm.synced_folder ".", "/vagrant", disabled: true
      node1.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end

    config.vm.define "node2" do |node2|
      node2.vm.network :private_network, ip: "192.168.56.151"
      node2.vm.hostname = "node2.otus.local"
      node2.vm.synced_folder ".", "/vagrant", disabled: true
      node2.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end

    config.vm.define "node3" do |node3|
      node3.vm.network :private_network, ip: "192.168.56.152"
      node3.vm.hostname = "node3.otus.local"
      node3.vm.synced_folder ".", "/vagrant", disabled: true
      node3.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end

    config.vm.define "controller" do |controller|
      controller.vm.network :private_network, ip: "192.168.56.140"
      controller.vm.hostname = "controller.otus.local"
      controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
    end
end