FROM alpine:latest
RUN apk add --update nginx && rm -rf /var/cache/apk/* && mkdir -p /run/nginx
COPY default.conf /etc/nginx/conf.d/default.conf
COPY ./html/index.html /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]