Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
  
    config.vm.define "server" do |server|
      server.vm.network :private_network, ip: "192.168.56.150"
      server.vm.hostname = "server.otus.local"
      server.vm.synced_folder ".", "/vagrant", disabled: true
      server.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end
  
    config.vm.define "client" do |client|
      client.vm.network :private_network, ip: "192.168.56.151"
      client.vm.hostname = "client.otus.local"
      client.vm.synced_folder ".", "/vagrant", disabled: true
      client.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end
  
    config.vm.define "controller" do |controller|
      controller.vm.network :private_network, ip: "192.168.56.140"
      controller.vm.hostname = "controller.otus.local"
      controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
    end
  end