Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
    
      config.vm.define "ipa" do |ipa|
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", "2048"]
          v.customize ["modifyvm", :id, "--cpus", "2"]
        end
        ipa.vm.network :private_network, ip: "192.168.11.13", dns: "192.168.11.13"
        ipa.vm.hostname = "ipa.otus.local"
        ipa.vm.synced_folder ".", "/vagrant", disabled: true
        ipa.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
        ipa.vm.provision "shell", privileged: false, path: "./scripts/ipa-add-hosts.sh"
        ipa.vm.provision "shell", privileged: false, path: "./scripts/install-chrony.sh"
      end

      config.vm.define "cl01" do |cl01|
        cl01.vm.network :private_network, ip: "192.168.11.14"
        cl01.vm.hostname = "cl01.otus.local"
        cl01.vm.synced_folder ".", "/vagrant", disabled: true
        cl01.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
      end

      config.vm.define "controller" do |controller|
        controller.vm.network :private_network, ip: "192.168.11.15"
        controller.vm.hostname = "controller.otus.local"
        controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
        controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
        controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-hosts.sh"
        #controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
      end
end