# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
  
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
    end
  
    config.vm.define "ns01" do |ns01|
      ns01.vm.network "private_network", ip: "192.168.56.150", virtualbox__intnet: "dns"
      ns01.vm.hostname = "ns01"
    end
end