# -*- mode: ruby -*-
# vi: set ft=ruby :
# MySQL - бэкап, репликация, кластер

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
  
    config.vm.define "mysql01" do |mysql01|
      mysql01.vm.network :private_network, ip: "192.168.56.150"
      mysql01.vm.hostname = "mysql01.otus.local"
      mysql01.vm.synced_folder ".", "/vagrant", disabled: true
      mysql01.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end

    config.vm.define "controller" do |controller|
      controller.vm.network :private_network, ip: "192.168.56.140"
      controller.vm.hostname = "controller.otus.local"
      controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
    end
end