# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        :net => [
                    {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :inetRouter2 => {
    :box_name => "centos/7",
    :net => [
                {ip: '192.168.252.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
            ],
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [  {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                   {ip: '192.168.252.1', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
                ]
  },

  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                ]
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/inetRouter.sh"

        when "inetRouter2"
          box.vm.network 'forwarded_port', guest: 80, host: 8080, host_ip: '127.0.0.1'
          box.vm.provision "shell", privileged: true, path: "./scripts/inetRouter2.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"

        when "centralRouter"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/centralRouter.sh"

        when "centralServer"
          box.vm.provision "shell", privileged: true, path: "./scripts/centralServer.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
          
        end
      end
  end
end