  MACHINES = {
    :docker => {
          :box_name => "centos/7",
          :ip_addr => '192.168.11.101'
    }
  }
  Vagrant.configure("2") do |config|
    MACHINES.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "forwarded_port", guest: 80, host: 80
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provision :docker
            box.vm.provision :docker_compose, rebuild: true, run: "always", yml: "/vagrant/docker-compose.yml"
        end
    end
  end