Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.define "systemd" do |systemd|
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", "4096"]
      end
      systemd.vm.network :private_network, ip: "192.168.56.150"
      systemd.vm.hostname = "systemd.otus.local"
      systemd.vm.synced_folder ".", "/vagrant", disabled: true
      systemd.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
    end

    config.vm.define "controller" do |controller|
      controller.vm.network :private_network, ip: "192.168.56.140"
      controller.vm.hostname = "controller.otus.local"
      controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
    end
end