# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
SERVERS = 
{
    :lesson02 => 
    {
        :box_name => "centos/7",
        :disks => 
        {
            :sata1 => 
            {
                :dfile => home + '/VirtualBox VMs/sata1.vdi',
                :size => 1024, # Megabytes
                :port => 1
            },
            :sata2 => 
            {
                :dfile => home + '/VirtualBox VMs/sata2.vdi',
                :size => 1024, # Megabytes
                :port => 2
            },
            :sata3 => 
            {
                :dfile => home + '/VirtualBox VMs/sata3.vdi',
                :size => 1024, # Megabytes
                :port => 3
            },
            :sata4 => 
            {
                :dfile => home + '/VirtualBox VMs/sata4.vdi',
                :size => 1024, # Megabytes
                :port => 4
            },
            :sata5 => 
            {
                :dfile => home + '/VirtualBox VMs/sata5.vdi',
                :size => 1024, # Megabytes
                :port => 5
            },
            :sata6 => 
            {
                :dfile => home + '/VirtualBox VMs/sata6.vdi',
                :size => 1024, # Megabytes
                :port => 6
            }
        }
    },
}
Vagrant.configure("2") do |config|
    SERVERS.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
                needsController = false
                    boxconfig[:disks].each do |dname, dconf|
                        unless File.exist?(dconf[:dfile])
                            vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                            needsController =  true
                        end
                    end
                    if needsController == true
                        vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                        boxconfig[:disks].each do |dname, dconf|
                            vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                        end
                    end
            end
            box.vm.provision "shell", path: "./create_raid10.sh"
        end
    end
end