# -*- mode: ruby -*-
# vim: set ft=ruby :
MACHINES = {
  :inetRouter => {
        :box_name => "centos/7",
        :net => [
                    {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [  {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.254.1', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.253.1', adapter: 4, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                   {ip: '192.168.0.1', adapter: 5, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                ]
  },

  :office1Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.254.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
               {ip: '192.168.2.65', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "test servers1"},
            ]
  },

  :office2Router => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.253.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
               {ip: '192.168.1.129', adapter: 3, netmask: "255.255.255.192", virtualbox__intnet: "test servers2"},
            ]
  },

  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                ]
  },

  :office1Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.2.66', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test servers1"},
            ]
  },

  :office2Server => {
    :box_name => "centos/7",
    :net => [
               {ip: '192.168.1.130', adapter: 2, netmask: "255.255.255.192", virtualbox__intnet: "test servers2"},
            ]
  },

  :controller => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.3', adapter: 3, netmask: "255.255.255.240", virtualbox__intnet: "central-net"},
                ]
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", privileged: true, path: "./scripts/inetRouter.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"

        when "centralRouter"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/centralRouter.sh"

        when "office1Router"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/office1Router.sh"
        
        when "office2Router"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/office2Router.sh"

        when "centralServer"
          box.vm.provision "shell", privileged: true, path: "./scripts/centralServer.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"

        when "office1Server"
          box.vm.provision "shell", privileged: true, path: "./scripts/office1Server.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"

        when "office2Server"
          box.vm.provision "shell", privileged: true, path: "./scripts/office2Server.sh"
          box.vm.provision "shell", privileged: true, path: "./scripts/install-script.sh"

        when "controller"
          box.vm.network :private_network, ip: "192.168.56.50"
          box.vm.provision "shell", privileged: false, path: "./scripts/controller.sh"
          box.vm.provision "shell", privileged: false, path: "./scripts/enable-passwd-ssh.sh"
          box.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
          box.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
        end
      end
  end
end