Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
    
      config.vm.define "client" do |client|
        client.vm.network :private_network, ip: "192.168.11.20"
        client.vm.hostname = "client.otus.local"
        client.vm.synced_folder ".", "/vagrant", disabled: true
        client.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
      end

      config.vm.define "prometheus" do |prometheus|
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", "512"]
        end
        prometheus.vm.network :private_network, ip: "192.168.11.21"
        prometheus.vm.hostname = "log.otus.local"
        prometheus.vm.synced_folder ".", "/vagrant", disabled: true
        prometheus.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
      end

      config.vm.define "zabbix" do |zabbix|
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", "512"]
        end
        zabbix.vm.network :private_network, ip: "192.168.11.22"
        zabbix.vm.hostname = "log.otus.local"
        zabbix.vm.synced_folder ".", "/vagrant", disabled: true
        zabbix.vm.provision "shell", privileged: false, path: "./scripts/install-script.sh"
      end

      config.vm.define "controller" do |controller|
        controller.vm.network :private_network, ip: "192.168.11.30"
        controller.vm.hostname = "controller.otus.local"
        controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
        controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      end
end