# -*- mode: ruby -*-
# vim: set ft=ruby :
SERVERS = 
{
    :bash => 
    {
        :box_name => "centos/7",
        :box_version => "1804.02"
    }
}
Vagrant.configure("2") do |config|
    config.vm.box_version = "1804.02"
    SERVERS.each do |boxname, boxconfig|
        config.vm.define boxname do |box|
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.provider :virtualbox do |vb|
                vb.customize ["modifyvm", :id, "--memory", "1024"]
            end
        end
    end
end
