Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
    
      config.vm.define "web" do |web|
        web.vm.network :private_network, ip: "192.168.11.13"
        web.vm.hostname = "web.otus.local"
        web.vm.synced_folder ".", "/vagrant", disabled: true
        web.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
        web.vm.provision "shell", privileged: false, path: "./scripts/install-rsyslog.sh"
      end

      config.vm.define "log" do |log|
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--memory", "4096"]
        end
        log.vm.network :private_network, ip: "192.168.11.14"
        log.vm.hostname = "log.otus.local"
        log.vm.synced_folder ".", "/vagrant", disabled: true
        log.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
        log.vm.provision "shell", privileged: false, path: "./scripts/install-rsyslog.sh"
      end

      config.vm.define "controller" do |controller|
        controller.vm.network :private_network, ip: "192.168.11.15"
        controller.vm.hostname = "controller.otus.local"
        controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
        controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
        controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
      end
end