Vagrant.configure("2") do |config|
      config.vm.box = "centos/7"
    
      config.vm.define "web" do |web|
        web.vm.network :private_network, ip: "192.168.11.13"
        web.vm.hostname = "web.oyus.local"
        web.vm.synced_folder ".", "/vagrant", disabled: true
        #web.vm.provision "shell", privileged: false, path: "./scripts/enable-ssh-pass.sh"
        web.vm.provision "shell", privileged: false, inline: <<-EOF
        sudo yum -y install wget
        wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -O /tmp/id_rsa.pub
        cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        EOF
      end
      config.vm.define "elk" do |elk|
        config.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--memory", "4096"]
        end
        elk.vm.network :private_network, ip: "192.168.11.14"
        elk.vm.hostname = "elk.otus.local"
        elk.vm.synced_folder ".", "/vagrant", disabled: true
        #elkvm.provision "shell", privileged: false, path: "./scripts/enable-ssh-pass.sh"
        elk.vm.provision "shell", privileged: false, inline: <<-EOF
        sudo yum -y install wget
        wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -O /tmp/id_rsa.pub
        cat /tmp/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
        EOF
      end
      #
      # this is our ansible controller VM which provisions the other VMs
      #
      config.vm.define "controller" do |controller|
        controller.vm.network :private_network, ip: "192.168.11.15"
        controller.vm.hostname = "controller.otus.local"
        # install ansible
        controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
        # run ansible
        controller.vm.provision "shell", privileged: false, inline: <<-EOF
        sudo yum -y install wget
          if [ ! -f /home/vagrant/.ssh/id_rsa ]; then
            wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant -O /home/vagrant/.ssh/id_rsa
            wget --no-check-certificate https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub -O /home/vagrant/.ssh/id_rsa.pub
            chmod 600 /home/vagrant/.ssh/id_*
          fi
        EOF
      end
    end