Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
  
    config.vm.define "mail" do |mail|
      mail.vm.network :private_network, ip: "192.168.11.20"
      mail.vm.hostname = "mail.otus.local"
      mail.vm.network "forwarded_port", guest: 25, host: 10025
      mail.vm.network "forwarded_port", guest: 143, host: 10143
      mail.vm.synced_folder ".", "/vagrant", disabled: true
      mail.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
      mail.vm.provision "shell", privileged: false, path: "./scripts/install-chrony.sh"
    end

    config.vm.define "cl01" do |cl01|
      cl01.vm.network :private_network, ip: "192.168.11.25", dns: "192.168.11.25"
      cl01.vm.hostname = "cl01.otus.local"
      cl01.vm.synced_folder ".", "/vagrant", disabled: true
      cl01.vm.provision "shell", privileged: false, path: "./scripts/add-ssh-cert.sh"
      cl01.vm.provision "shell", privileged: false, path: "./scripts/install-chrony.sh"
    end

    config.vm.define "controller" do |controller|
      controller.vm.network :private_network, ip: "192.168.11.30"
      controller.vm.hostname = "controller.otus.local"
      controller.vm.provision "shell", privileged: false, path: "./scripts/controller-add-ssh-cert.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/install-ansible.sh"
      controller.vm.provision "shell", privileged: false, path: "./scripts/playbook.sh"
    end
end