---
all:
  children:
    ospf:

ospf:
  hosts:
    r1:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_ssh_private_key_file: .vagrant/machines/r1/virtualbox/private_key
    r2:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_ssh_private_key_file: .vagrant/machines/r2/virtualbox/private_key
    r3:
      ansible_host: 127.0.0.1
      ansible_port: 2201
      ansible_ssh_private_key_file: .vagrant/machines/r3/virtualbox/private_key